[theme]
base = "light"
primaryColor = "#1A4373"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F4F8FD"
textColor = "#0F1729"
font = "sans serif"

[server]
headless = true
enableXsrfProtection = true

[browser]
gatherUsageStats = false
